### ISSUE TITLE
[Question] Some incorrect vocab_size  may confuse me.

### ISSUE THREAD

**Issue by LeeOrange-is-me** [dirtycomputer/O2M_attack#2]
I just run `run_jailbreak.py` by using `pyhton run_jailbreak.py`.

but it turns out that:
``` APL
IndexError: index out of range in self
```
I find that, the vocab_size is 32000, but there are 32001 and many 32000 in the tensor `input_ids` in function `opti_utils.py:get_embeddings(model,input_ids)`.

And I wanna why that was that, and seek for help...

**Comment by dirtycomputer** [comment]
how did you download the model weights
